# Generated by Django 4.2.3 on 2025-06-11 19:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='identificador',
        ),
        migrations.AlterField(
            model_name='servico',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
