# Generated by Django 4.1.7 on 2023-04-07 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regiaoservico',
            old_name='titulo',
            new_name='cidade',
        ),
    ]
