# Generated by Django 4.1.7 on 2023-04-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_alter_servico_protocolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='protocolo',
            field=models.CharField(blank=True, max_length=54, null=True),
        ),
    ]
