# Generated by Django 4.1.7 on 2023-04-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_alter_servico_protocolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='finalizado',
            field=models.BooleanField(default=True),
        ),
    ]
